using System.ComponentModel;

namespace NakClean.Services;

/// <summary>
/// Локализация (рус/англ). Привязка в XAML: {Binding [key], Source={x:Static loc:Loc.I}}.
/// Смена языка обновляет все привязки вживую.
/// </summary>
public sealed class Loc : INotifyPropertyChanged
{
    public static Loc I { get; } = new();

    private string _lang = "ru";
    public string Lang
    {
        get => _lang;
        set
        {
            if (_lang == value) return;
            _lang = value;
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs("Item[]"));
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(Lang)));
        }
    }

    public bool IsEn => _lang == "en";
    public string this[string key] => (_lang == "en" ? En : Ru).TryGetValue(key, out var v) ? v : key;

    /// <summary>Склонение слова из ключа вида "ядро|ядра|ядер".</summary>
    public string Plural(int n, string key)
    {
        var p = this[key].Split('|');
        return p.Length < 3 ? this[key] : Format.Plural(n, p[0], p[1], p[2]);
    }

    public event PropertyChangedEventHandler? PropertyChanged;

    private static readonly Dictionary<string, string> Ru = new()
    {
        ["nav_overview"] = "Обзор системы",
        ["nav_check"] = "Проверка ПК",
        ["nav_clean"] = "Очистка",
        ["nav_optimize"] = "Оптимизация",
        ["nav_registry"] = "Реестр",
        ["nav_startup"] = "Запуск",
        ["nav_apps"] = "Удаление программ",
        ["nav_files"] = "Поиск файлов",
        ["nav_health"] = "Здоровье дисков",
        ["nav_about"] = "О программе",
        ["nav_maint"] = "Обслуживание",
        ["nav_diag"] = "Диагностика",
        ["nav_recovery"] = "Восстановление",
        ["rec_note"] = "Выбери диск и нажми «Поиск удалённых». Восстанавливай только на ДРУГОЙ диск.",
        ["rec_scan"] = "🔍  Поиск удалённых", ["rec_scanning"] = "Сканирую удалённые файлы…",
        ["rec_found"] = "Найдено удалённых файлов: {0}", ["rec_empty"] = "Удалённых файлов не найдено",
        ["rec_all"] = "Все",
        ["rec_recover"] = "♻  Восстановить выбранное", ["rec_recovering"] = "Восстанавливаю…",
        ["rec_done"] = "Восстановлено: {0}, не удалось: {1}", ["rec_nosel"] = "Ничего не выбрано",
        ["rec_pickdest"] = "Куда восстановить (папка на ДРУГОМ диске)",
        ["rec_samedrive"] = "Нельзя восстанавливать на тот же диск - выбери другой",
        ["rec_hint"] = "⚠ Восстанавливай на ДРУГОЙ диск - иначе данные можно затереть.",
        ["rec_high"] = "высокий", ["rec_mid"] = "средний", ["rec_low"] = "низкий", ["rec_wiped"] = "стёрт",
        ["rcat_img"] = "🖼 Фото и картинки", ["rcat_video"] = "🎬 Видео", ["rcat_audio"] = "🎵 Музыка",
        ["rcat_doc"] = "📄 Документы", ["rcat_archive"] = "🗜 Архивы", ["rcat_prog"] = "⚙ Программы и библиотеки",
        ["rcat_other"] = "📦 Прочее",
        ["header_subtitle"] = "очистка и оптимизация",
        // диагностика — батарея
        ["hdr_diag"] = "Диагностика",
        ["report_btn"] = "📄 Паспорт ПК",
        ["rep_title"] = "Паспорт ПК",
        ["rep_generated"] = "Сгенерировано",
        ["rep_os"] = "Система",
        ["rep_saved"] = "Сохранено: {0}",
        ["bat_title"] = "Здоровье батареи",
        ["bat_reading"] = "Читаю отчёт о батарее…",
        ["bat_none"] = "Батарея не обнаружена (стационарный ПК).",
        ["bat_summary"] = "Износ {0}% от проектной ёмкости.",
        ["bat_wear"] = "Износ",
        ["bat_cycles"] = "Циклов заряда",
        ["bat_cyc_na"] = "нет данных",
        ["bat_design"] = "Проектная ёмкость",
        ["bat_full"] = "Текущая макс. ёмкость",
        ["bat_charge"] = "Заряд", ["bat_serial"] = "S/N {0}",
        ["bat_st_charging"] = "заряжается", ["bat_st_ac"] = "от сети", ["bat_st_batt"] = "от батареи",
        ["bat_health_great"] = "Отличное состояние", ["bat_health_ok"] = "Норма, в рабочем состоянии",
        ["bat_health_bad"] = "Сильный износ - стоит задуматься о замене",
        ["u_wh"] = "Вт·ч",
        // диагностика — время загрузки
        ["boot_title"] = "Время загрузки",
        ["boot_reading"] = "Читаю журнал загрузки…",
        ["boot_none"] = "Нет данных о загрузке (журнал пуст или недоступен).",
        ["boot_time"] = "Последняя загрузка заняла {0} с.",
        ["boot_slow_head"] = "Что замедлило загрузку:",
        ["boot_slow_hint"] = "Вклад каждого в запуск (учитывает и фоновую догрузку) - может быть больше общего времени.",
        ["boot_noslow"] = "Замедлений не обнаружено.",
        ["u_sec"] = "с",
        ["boot_kind_app"] = "приложение",
        ["boot_kind_driver"] = "драйвер",
        ["boot_kind_service"] = "служба",
        // обслуживание
        ["hdr_maint"] = "Обслуживание системы",
        ["mnt_note"] = "Системные инструменты Windows. Некоторые занимают несколько минут - окно остаётся отзывчивым.",
        ["mnt_run"] = "Запустить",
        ["mnt_running"] = "Выполняется…",
        ["mnt_done"] = "Готово.",
        ["mnt_done_freed"] = "Готово - хранилище компонентов очищено.",
        ["mnt_fail"] = "Не удалось (нужны права администратора?).",
        ["mnt_ram_launched"] = "Открыта диагностика памяти - следуй подсказке (нужна перезагрузка).",
        ["mnt_sfc"] = "Проверка системных файлов (SFC)",
        ["mnt_sfc_d"] = "Полная проверка системных файлов (несколько минут), восстановление повреждённых",
        ["mnt_dism"] = "Восстановление образа (DISM)",
        ["mnt_dism_d"] = "Проверка мгновенная; восстановление чинит хранилище компонентов Windows",
        ["mnt_winsxs"] = "Очистка хранилища компонентов (WinSxS)",
        ["mnt_winsxs_d"] = "Удаляет старые версии обновлений из WinSxS (часто гигабайты). Безопасно - программы и Windows не затрагиваются",
        ["mnt_defrag"] = "Оптимизация дисков",
        ["mnt_defrag_d"] = "Дефрагментация HDD и TRIM для SSD (как «Оптимизация дисков» Windows)",
        ["mnt_ram"] = "Тест оперативной памяти",
        ["mnt_ram_d"] = "Средство диагностики памяти Windows (потребует перезагрузку)",
        ["mnt_check"] = "Проверить",
        ["mnt_cancel"] = "Отмена",
        ["mnt_analyzed"] = "Проверка завершена. Запустить или отменить?",
        ["mnt_cancelled"] = "Отменено.",
        ["mnt_r_sfc_clean"] = "Повреждений системных файлов не обнаружено.",
        ["mnt_r_sfc_found"] = "Обнаружены повреждённые системные файлы - рекомендуется восстановление.",
        ["mnt_r_sfc_unfixable"] = "Повреждения найдены, но SFC не смог их починить - запусти DISM, затем SFC снова.",
        ["mnt_r_dism_clean"] = "Повреждений хранилища компонентов не обнаружено.",
        ["mnt_r_dism_repairable"] = "Обнаружены повреждения хранилища - рекомендуется восстановление.",
        ["mnt_r_winsxs_yes"] = "Есть устаревшие компоненты - очистка освободит место. Безопасно: удаляются только старые версии обновлений, программы и Windows не пострадают.",
        ["mnt_r_winsxs_yes_sz"] = "Можно освободить ≈{0}. Безопасно: удаляются только старые версии обновлений, программы и Windows не пострадают.",
        ["mnt_r_winsxs_no"] = "Очистка не требуется - хранилище в порядке.",
        ["mnt_st_sfc_check"] = "Проверяю системные файлы…",
        ["mnt_st_sfc_run"] = "Проверяю и восстанавливаю системные файлы…",
        ["mnt_st_dism_check"] = "Сканирую хранилище компонентов…",
        ["mnt_st_dism_run"] = "Восстанавливаю хранилище компонентов…",
        ["mnt_st_winsxs_check"] = "Анализирую хранилище компонентов…",
        ["mnt_st_winsxs_run"] = "Очищаю устаревшие компоненты…",
        ["mnt_st_defrag_check"] = "Анализирую фрагментацию дисков…",
        ["mnt_st_defrag_run"] = "Оптимизирую диски…",
        ["mnt_defrag_head"] = "Анализ дисков:",
        ["mnt_op_ssd"] = "SSD, оптимизация (TRIM)",
        ["mnt_op_hdd"] = "HDD, дефрагментация",
        ["mnt_op_line"] = "{0}: {1} - {2}, {3}",
        ["mnt_op_lastdays"] = "последняя {0} дн. назад",
        ["mnt_op_lasttoday"] = "оптимизирован сегодня",
        ["mnt_op_lastunknown"] = "дата последней неизвестна",
        ["mnt_op_need"] = "рекомендуется",
        ["mnt_op_ok"] = "не требуется",
        ["mnt_defrag_noinfo"] = "Не удалось прочитать данные о дисках.",
        ["about_tagline"] = "Честная очистка и оптимизация Windows",
        ["about_author"] = "Сделано by nak",
        ["about_version"] = "Версия",
        ["upd_check"] = "Проверить обновления", ["upd_checking"] = "Проверяю обновления…",
        ["upd_latest"] = "У вас последняя версия", ["upd_available"] = "Доступна новая версия {0}",
        ["upd_fail"] = "Не удалось проверить обновления", ["upd_download"] = "Скачать обновление",
        ["theme_tip"] = "Тема: тёмная / светлая",
        ["lang_tip"] = "Сменить язык",
        ["glass"] = "Стеклянный режим (Acrylic, Windows 11)",
        ["glass_hint"] = "Матовое стекло с размытием рабочего стола за окном.",
        // заголовки страниц
        ["hdr_overview"] = "Обзор системы",
        ["hdr_clean"] = "Очистка системы",
        ["hdr_optimize"] = "Оптимизация",
        ["hdr_registry"] = "Очистка реестра",
        ["hdr_startup"] = "Запуск",
        ["hdr_apps"] = "Удаление программ",
        ["hdr_files"] = "Поиск файлов",
        ["hdr_health"] = "Здоровье дисков (S.M.A.R.T.)",
        // плитки обзора
        ["tile_cpu"] = "Процессор",
        ["tile_ram"] = "Память",
        ["tile_gpu"] = "Видеокарта",
        ["tile_disk"] = "Диск",
        ["tile_battery"] = "Батарея",
        ["ov_os"] = "{0} · сборка {1}", ["ov_uptime"] = "работает {0}",
        ["cap_load"] = "загрузка",
        ["cap_used"] = "занято",
        ["w_cores"] = "ядро|ядра|ядер",
        ["w_threads"] = "поток|потока|потоков",
        ["w_modules"] = "планка|планки|планок",
        ["u_gb"] = "ГБ",
        ["u_ghz"] = "ГГц",
        ["u_mhz"] = "МГц",
        // здоровье дисков
        ["dh_temp"] = "ТЕМПЕРАТУРА",
        ["dh_hours"] = "ЧАСЫ РАБОТЫ",
        ["dh_wear"] = "ИЗНОС (SSD)",
        ["dh_errors"] = "ОШИБКИ",
        ["dh_admin"] = "⚠ Детальные показатели доступны при запуске от администратора",
        ["dh_note"] = "Дисков обнаружено: {0}. Данные актуальны.",
        ["dh_note_empty"] = "Диски не найдены (нужны права администратора).",
        ["dh_na"] = "не сообщается",
        ["dh_read"] = "чтение",
        ["dh_write"] = "запись",
        ["st_healthy"] = "Здоров",
        ["st_warning"] = "Предупреждение",
        ["st_unhealthy"] = "Проблемы",
        ["st_unknown"] = "Неизвестно",
        ["u_h"] = "ч",
        ["u_years"] = "лет",
        ["u_days"] = "дн.",
        // поиск файлов
        ["fs_tree"] = "Дерево",
        ["fs_files"] = "Файлы",
        ["fs_browse"] = "📁 Обзор…",
        ["fs_analyze"] = "🔎 Анализ",
        ["fs_up"] = "↑ Вверх",
        ["fs_c_folder"] = "ПАПКА",
        ["fs_c_percent"] = "ПРОЦЕНТ",
        ["fs_c_size"] = "РАЗМЕР",
        ["fs_c_disk"] = "НА ДИСКЕ",
        ["fs_c_files"] = "ФАЙЛЫ",
        ["fs_c_types"] = "ТИПЫ ФАЙЛОВ",
        ["fs_c_name"] = "ИМЯ",
        ["fs_c_folder2"] = "ПАПКА   (двойной клик - открыть, правый клик - меню)",
        // оптимизация
        ["opt_apply"] = "⚡ Применить выбранное",
        ["opt_revert"] = "↩ Откатить",
        ["opt_restore"] = "Создать точку восстановления перед применением",
        ["opt_note"] = "Выбери твики и нажми «Применить». Перед применением создаётся точка восстановления.",
        ["opt_applied"] = "Применено",
        ["opt_profiles"] = "Профили:",
        ["prof_balanced"] = "Сбалансированный",
        ["prof_gaming"] = "Игровой",
        ["prof_quiet"] = "Тихий",
        ["prof_clear"] = "Снять выбор",
        ["opt_profile_set"] = "Профиль отмечен: {0} твиков. Проверь и нажми «Применить».",
        ["opt_profile_cleared"] = "Выбор снят.",
        ["chg_count"] = "Журнал изменений: применено твиков — {0}",
        ["chg_revert_all"] = "↩ Откатить всё",
        ["chg_confirm"] = "Откатить все изменения из журнала ({0})? Система вернётся к состоянию до оптимизации.",
        ["chg_reverted"] = "Откачено изменений: {0}.",
        ["tier_safe"] = "Безопасно",
        ["tier_medium"] = "Средне",
        ["tier_max"] = "Максимум",
        ["tw_anim"] = "Отключить анимацию окон", ["tw_anim_d"] = "Ускоряет отклик интерфейса",
        ["tw_transp"] = "Отключить прозрачность", ["tw_transp_d"] = "Меньше нагрузка на GPU",
        ["tw_tips"] = "Отключить советы и подсказки Windows", ["tw_tips_d"] = "Убирает навязчивые уведомления",
        ["tw_startdelay"] = "Убрать задержку автозагрузки", ["tw_startdelay_d"] = "Программы автозапуска стартуют сразу",
        ["tw_explorerads"] = "Убрать рекламу в проводнике", ["tw_explorerads_d"] = "Отключает «уведомления поставщиков синхронизации»",
        ["tw_gamedvr"] = "Отключить Game DVR / запись игр", ["tw_gamedvr_d"] = "Меньше фоновых процессов в играх",
        ["tw_bgapps"] = "Отключить фоновые приложения", ["tw_bgapps_d"] = "Приложения не работают в фоне без надобности",
        ["tw_telemetry"] = "Снизить телеметрию", ["tw_telemetry_d"] = "Минимум сбора данных (политика)",
        ["tw_activity"] = "Отключить историю действий", ["tw_activity_d"] = "ОС не собирает ленту активности",
        ["tw_sysmain"] = "Отключить SysMain (Superfetch)", ["tw_sysmain_d"] = "Может ускорить SSD-системы; на HDD иногда полезен",
        ["tw_wsearch"] = "Отключить индексацию (Windows Search)", ["tw_wsearch_d"] = "Меньше нагрузки на диск; поиск станет медленнее",
        ["tw_diagtrack"] = "Отключить службу телеметрии (DiagTrack)", ["tw_diagtrack_d"] = "Полностью останавливает сбор диагностики",
        ["tw_hibernate"] = "Отключить гибернацию", ["tw_hibernate_d"] = "Освобождает место на диске (удаляет hiberfil.sys)",
        // новые твики (из пака, только реально работающие)
        ["tw_menudelay"] = "Мгновенное открытие меню", ["tw_menudelay_d"] = "MenuShowDelay=0 - меню открываются без задержки",
        ["tw_recording"] = "Отключить фоновую запись игр", ["tw_recording_d"] = "Game DVR перестаёт записывать в фоне - меньше нагрузки",
        ["tw_widgets"] = "Отключить виджеты (Windows 11)", ["tw_widgets_d"] = "Процесс виджетов не висит в фоне - экономия RAM/CPU",
        ["tw_startads"] = "Убрать рекламу и «рекомендации» в Пуске", ["tw_startads_d"] = "Рекламный ID + предложения ContentDeliveryManager",
        ["tw_bgsearch"] = "Полностью остановить фоновые приложения", ["tw_bgsearch_d"] = "Добивает фоновые UWP-приложения (тоггл поиска)",
        ["tw_netthrottle"] = "Отключить сетевой троттлинг", ["tw_netthrottle_d"] = "Помогает связке звук/видео + сеть (стримы, онлайн)",
        ["tw_vbs"] = "Отключить VBS (Memory Integrity)", ["tw_vbs_d"] = "Реальный прирост 5-15%, НО снижает защиту памяти",
        // честные метки эффекта
        ["eff_notable"] = "заметный", ["eff_small"] = "небольшой", ["eff_space"] = "+место",
        ["eff_security"] = "−безопасность", ["eff_convenience"] = "удобство",
        ["eff_notable_tip"] = "Заметный прирост производительности - реально чувствуется.",
        ["eff_small_tip"] = "Небольшой, но настоящий эффект: чуть быстрее отклик или меньше расход RAM/CPU. Не ждите скачка FPS.",
        ["eff_space_tip"] = "Освобождает место на диске (на скорость не влияет).",
        ["eff_security_tip"] = "Ускоряет, НО снижает защиту системы. Включайте осознанно, на свой риск.",
        ["eff_convenience_tip"] = "Влияет на удобство и приватность, а не на скорость работы.",
        // общие кнопки/колонки
        ["btn_enable"] = "Включить", ["btn_disable"] = "Выключить", ["btn_delete"] = "Удалить",
        ["btn_select_all"] = "Выбрать всё", ["btn_select_none"] = "Снять всё", ["btn_refresh"] = "↻  Обновить",
        ["btn_scan"] = "🔍  Сканировать", ["btn_clean"] = "🧹  Очистить",
        ["c_on"] = "ВКЛ", ["c_program"] = "ПРОГРАММА", ["c_publisher"] = "ИЗДАТЕЛЬ", ["c_location"] = "РАСПОЛОЖЕНИЕ",
        ["c_command"] = "КОМАНДА", ["c_name"] = "НАЗВАНИЕ", ["c_author"] = "АВТОР", ["c_state"] = "СОСТОЯНИЕ",
        ["c_service"] = "СЛУЖБА", ["c_iname"] = "ИМЯ", ["c_start"] = "ЗАПУСК", ["c_menuitem"] = "ПУНКТ МЕНЮ", ["c_where"] = "ГДЕ",
        ["tip_expand"] = "Развернуть/свернуть",
        // проверка пк
        ["pc_state"] = "Состояние ПК", ["pc_recheck"] = "🔄  Проверить заново",
        ["verdict_great"] = "Отличное состояние", ["verdict_good"] = "Хорошее, есть что улучшить",
        ["verdict_attention"] = "Требует внимания", ["verdict_bad"] = "Много проблем",
        ["pc_problems"] = "Проблемы", ["pc_warnings"] = "Внимание", ["pc_ok"] = "В норме",
        // очистка
        ["clean_admin"] = "нужны права админа", ["clean_selected"] = "К очистке выбрано",
        ["sess_freed"] = "✓ За сессию освобождено: {0}",
        ["grp_system"] = "Система", ["grp_browsers"] = "Браузеры",
        ["det_scanning"] = "сканирование…", ["det_unscanned"] = "не просканировано",
        ["det_items"] = "элементов", ["det_files"] = "файлов",
        // реестр
        ["reg_scan"] = "🔍  Поиск проблем", ["reg_fix"] = "🛠  Исправить выбранное", ["reg_notfound"] = "Запись не найдена",
        // запуск
        ["st_apps"] = "Программы", ["st_tasks"] = "Задачи", ["st_svc"] = "Службы", ["st_ctx"] = "Контекстное меню",
        ["st_yes"] = "Да", ["st_no"] = "Нет",
        // удаление программ
        ["un_uninstall"] = "Деинсталляция", ["un_repair"] = "Восстановить", ["un_rename"] = "Переименовать", ["un_remove"] = "Убрать из списка",
        ["uc_program"] = "ПРОГРАММА ▾", ["uc_publisher"] = "ИЗДАТЕЛЬ ▾", ["uc_installed"] = "УСТАНОВЛЕНА ▾", ["uc_size"] = "РАЗМЕР ▾", ["uc_version"] = "ВЕРСИЯ ▾",
        // реестр - причины
        ["rp_dll"] = "Файл библиотеки не найден", ["rp_prog"] = "Программа не найдена",
        ["rp_handler"] = "Нет обработчика «{0}»", ["rp_uninst"] = "Деинсталлятор не найден ({0})",
        ["rp_startup"] = "Файл автозагрузки не найден", ["rp_font"] = "Файл шрифта не найден",
        ["rp_sound"] = "Звуковой файл не найден", ["rp_help"] = "Файл справки не найден",
        // проверка ПК - категории/пункты
        ["hc_mem"] = "Память", ["hc_disks"] = "Диски", ["hc_sec"] = "Безопасность", ["hc_hw"] = "Оборудование", ["hc_sys"] = "Система",
        ["hm_t"] = "Загрузка оперативной памяти", ["hm_v"] = "{0}%  ({1} из {2})", ["hm_h"] = "Закрой неиспользуемые программы или добавь ОЗУ.",
        ["hm_installed"] = "· установлено {0}",
        ["hd_t"] = "Свободное место - {0}", ["hd_v"] = "{0} свободно ({1}%)", ["hd_h"] = "Освободи место - почисти мусор или перенеси файлы.",
        ["hs_h"] = "Диск может скоро выйти из строя - сделай резервную копию!",
        ["hf_t"] = "Защитник Windows", ["hf_on"] = "Включён, защита в реальном времени активна (базы: {0} дн.)",
        ["hf_on_fresh"] = "Включён, защита в реальном времени активна (базы актуальны)",
        ["hf_off"] = "Защита отключена", ["hf_err"] = "Не удалось проверить (возможно, нужен запуск от админа или стоит сторонний антивирус)",
        ["hf_h_bad"] = "Включи антивирус или установи сторонний.", ["hf_h_warn"] = "Обнови антивирусные базы.",
        ["hdr_t"] = "Драйверы устройств", ["hdr_ok"] = "Проблем не обнаружено", ["hdr_bad"] = "Устройств с ошибками: {0}",
        ["hdr_h"] = "Проверь Диспетчер устройств - есть устройства с проблемами.",
        ["hu_t"] = "Время работы без перезагрузки", ["hu_vd"] = "{0} дн. {1} ч", ["hu_vh"] = "{0} ч {1} мин",
        ["hu_h"] = "Давно не перезагружался - перезагрузка освежит систему.",
        ["hb_t"] = "Батарея", ["hb_v"] = "Заряд: {0}%", ["hb_none"] = "Не обнаружена (стационарный ПК)",
        ["hj_t"] = "Временные файлы (%TEMP%)", ["hj_v"] = "{0} мусора", ["hj_h"] = "Открой вкладку «Очистка» и удали мусор.",
        ["ho_t"] = "Операционная система", ["ho_v"] = "{0} (сборка {1})",
        ["note_status"] = "Готов к работе. Нажми «Сканировать», чтобы оценить мусор.",
        ["note_reg"] = "Выбери категории и нажми «Поиск проблем». Перед удалением создаётся резервная копия.",
        ["note_scan"] = "Выбери диск или папку и нажми «Анализ».",
        ["note_healthcheck"] = "Идёт проверка системы…",
        ["cap_of100"] = "из 100",
        // about (динамика)
        ["about_version_fmt"] = "Версия {0}",
        // runtime - общее
        ["err"] = "Ошибка: {0}",
        // проверка ПК
        ["hc_ok"] = "Проблем не обнаружено.",
        ["hc_found"] = "Найдено замечаний: {0}. Подробности ниже.",
        ["hc_err"] = "Ошибка проверки: {0}",
        // автозагрузка
        ["su_default"] = "Программы, запускающиеся вместе с Windows.",
        ["su_count"] = "Записей: {0} (включено: {1}).",
        ["su_on"] = "«{0}» включена в автозагрузке.",
        ["su_off"] = "«{0}» отключена.",
        ["su_fail_admin"] = "Не удалось изменить «{0}» - запусти NakClean от администратора.",
        ["su_fail"] = "Не удалось изменить «{0}».",
        ["su_del_q"] = "Удалить «{0}» из автозагрузки?\nЭто уберёт запись насовсем (программа не удаляется).",
        ["su_deleted"] = "«{0}» удалена из автозагрузки.",
        ["su_del_fail_admin"] = "Не удалось удалить «{0}» - нужны права администратора.",
        ["su_del_fail"] = "Не удалось удалить «{0}».",
        // удаление программ
        ["ap_default"] = "Установленные программы.",
        ["ap_count"] = "Установлено программ: {0}.",
        ["ap_repair_ok"] = "Запущено восстановление «{0}».",
        ["ap_repair_no"] = "Восстановление «{0}» недоступно.",
        ["ap_rename_prompt"] = "Новое название записи:",
        ["ap_renamed"] = "Запись переименована.",
        ["ap_rename_fail"] = "Не удалось переименовать - возможно, нужны права администратора.",
        ["ap_remove_q"] = "Убрать «{0}» из списка?\nЭто удалит только запись в реестре - сама программа НЕ удаляется.",
        ["ap_removed"] = "Запись убрана из списка.",
        ["ap_remove_fail"] = "Не удалось убрать запись - возможно, нужны права администратора.",
        ["ap_uninst_q"] = "Запустить деинсталлятор «{0}»?",
        ["ap_uninst_ok"] = "Запущен деинсталлятор «{0}». Следуй его инструкциям, затем нажми «Обновить».",
        ["ap_uninst_fail"] = "Не удалось запустить деинсталлятор «{0}».",
        // реестр
        ["reg_nocat"] = "Не выбрано ни одной категории.",
        ["reg_scanning"] = "Поиск проблем в реестре…",
        ["reg_clean"] = "Проблем не найдено - реестр чист.",
        ["reg_found"] = "Найдено проблем: {0}. Проверь список и нажми «Исправить выбранное».",
        ["reg_scan_err"] = "Ошибка сканирования: {0}",
        ["reg_nofix"] = "Ничего не выбрано для исправления.",
        ["reg_fix_q"] = "Будет создана резервная копия (.reg) и удалено записей: {0}.\nОткатить можно будет двойным кликом по файлу бэкапа.\n\nПродолжить?",
        ["reg_fix_title"] = "NakClean - очистка реестра",
        ["reg_fixing"] = "Создаю резервную копию и удаляю записи…",
        ["reg_removed"] = "Удалено: {0}.",
        ["reg_failed"] = " Не удалось: {0} (возможно, нужны права админа).",
        ["reg_backup_saved"] = " Резервная копия сохранена.",
        ["reg_done_box"] = "Готово.\nУдалено записей: {0}\nНе удалось: {1}\n\nРезервная копия:\n{2}\n\nЧтобы вернуть всё назад - закрой NakClean и дважды кликни по этому .reg-файлу.",
        ["reg_fix_err"] = "Ошибка при исправлении: {0}",
        // запланированные задачи
        ["tk_default"] = "Запланированные задачи (не системные).",
        ["tk_count"] = "Задач: {0} (включено: {1}).",
        ["tk_on"] = "Задача «{0}» включена.",
        ["tk_off"] = "Задача «{0}» отключена.",
        ["tk_fail"] = "Не удалось изменить «{0}» - запусти от администратора.",
        ["tk_del_q"] = "Удалить задачу «{0}»?",
        ["tk_deleted"] = "Задача удалена.",
        ["tk_del_fail"] = "Не удалось удалить - нужны права администратора.",
        // службы
        ["sv_default"] = "Службы Windows. Осторожно: отключение системных служб может навредить.",
        ["sv_count"] = "Служб: {0}. Осторожно с отключением системных.",
        ["sv_enable_q"] = "Включить службу «{0}» (автозапуск + старт)?",
        ["sv_disable_q"] = "Отключить службу «{0}»?\nОтключение системной службы может нарушить работу Windows.",
        ["sv_title"] = "NakClean - службы",
        ["sv_applying"] = "Применяю…",
        ["sv_fail"] = "Не удалось изменить «{0}» - нужны права администратора.",
        ["sv_on_run"] = "«{0}» включена и запущена.",
        ["sv_on_notrun"] = "«{0}»: автозапуск включён (служба пока не запустилась).",
        ["sv_off_run"] = "«{0}»: запуск запрещён, остановится после перезагрузки.",
        ["sv_off_stop"] = "«{0}» отключена и остановлена.",
        // контекстное меню
        ["cx_default"] = "Пункты контекстного меню проводника.",
        ["cx_count"] = "Пунктов: {0} (включено: {1}).",
        ["cx_on"] = "«{0}» включён.",
        ["cx_off"] = "«{0}» отключён.",
        ["cx_fail"] = "Не удалось изменить «{0}» - нужны права администратора.",
        ["cx_del_q"] = "Удалить пункт «{0}» из контекстного меню?\nБудет создана резервная копия .reg.",
        ["cx_deleted"] = "Пункт удалён (есть резервная копия).",
        ["cx_del_fail"] = "Не удалось удалить - нужны права администратора.",
        // оптимизация
        ["opt_none"] = "Ничего не выбрано.",
        ["opt_max_q"] = "Среди выбранного есть твики уровня «Максимум» - они меняют поведение системных служб.\nВсё обратимо. Продолжить?",
        ["opt_title"] = "NakClean - оптимизация",
        ["opt_rp_creating"] = "Создаю точку восстановления…",
        ["opt_rp_name"] = "NakClean - перед оптимизацией",
        ["opt_rp_ok"] = " Точка восстановления создана.",
        ["opt_rp_fail"] = " Точку создать не удалось (включи Защиту системы в свойствах ПК).",
        ["opt_applying"] = "Применяю…",
        ["opt_reverting"] = "Откатываю…",
        ["opt_applied_n"] = "Применено: {0}/{1}.",
        ["opt_reverted_n"] = "Откатано: {0}/{1}.",
        ["opt_after"] = " Часть изменений вступит в силу после перезахода/перезагрузки.",
        // поиск файлов
        ["fs_notarget"] = "- не выбрано -",
        ["fs_localdisk"] = "Локальный диск",
        ["fs_pickfolder"] = "Выбери папку для анализа",
        ["fs_badpath"] = "Папка или диск не найдены - проверь путь.",
        ["fs_analyzing"] = "Анализ…",
        ["fs_stats"] = "Файлов: {0}   ·   Размер: {1}   ·   На диске: {2}",
        ["fs_drive"] = "Том: занято {0} из {1} ({2}%), свободно {3}",
        ["fs_done"] = "Готово за {0} с.",
        ["map_title"] = "Карта диска появится после анализа",
        // очистка
        ["cl_scanning"] = "Сканирование…",
        ["cl_found"] = "Найдено мусора: {0}. Проверь выбор и нажми «Очистить».",
        ["cl_cancelled"] = "Сканирование отменено.",
        ["cl_scan_err"] = "Ошибка при сканировании: {0}",
        ["cl_cleaning"] = "Очистка…",
        ["cl_done"] = "Готово. Освобождено: {0}.",
        ["cl_interrupted"] = "Очистка прервана. Освобождено: {0}.",
        ["cl_clean_err"] = "Ошибка при очистке: {0}",
        // контекстное меню файлов (правый клик в Поиске файлов)
        ["ctx_open"] = "Открыть",
        ["ctx_open_folder"] = "Открыть папку",
        ["ctx_reveal"] = "Показать в Проводнике",
        ["ctx_openwith"] = "Открыть с помощью…",
        ["ctx_copypath"] = "Копировать путь",
        ["ctx_props"] = "Свойства",
        // службы - режим запуска
        ["sm_auto"] = "Авто",
        ["sm_manual"] = "Вручную",
        ["sm_disabled"] = "Отключена",
        // автозагрузка - источник
        ["su_folder_user"] = "Папка (пользователь)",
        ["su_folder_common"] = "Папка (общая)",
        // контекстное меню - где
        ["cmw_files"] = "Файлы",
        ["cmw_folders"] = "Папки",
        ["cmw_folderbg"] = "Фон папки",
        ["cmw_drives"] = "Диски",
        ["cmw_allobjects"] = "Все объекты",
        // поиск файлов - типы
        ["fs_noext"] = "(без расширения)",
        ["fs_typefile"] = "Файл",
        ["fs_typesuffix"] = "-файл",
        // прочее
        ["na"] = "н/д",
        ["u_mb"] = "МБ",
        ["app_error"] = "Произошла ошибка, но приложение продолжит работу:\n\n{0}",
    };

    private static readonly Dictionary<string, string> En = new()
    {
        ["nav_overview"] = "System Overview",
        ["nav_check"] = "PC Health",
        ["nav_clean"] = "Cleanup",
        ["nav_optimize"] = "Optimize",
        ["nav_registry"] = "Registry",
        ["nav_startup"] = "Startup",
        ["nav_apps"] = "Uninstall",
        ["nav_files"] = "File Search",
        ["nav_health"] = "Disk Health",
        ["nav_about"] = "About",
        ["nav_maint"] = "Maintenance",
        ["nav_diag"] = "Diagnostics",
        ["nav_recovery"] = "Recovery",
        ["rec_note"] = "Pick a drive and click Scan. Recover ONLY to a different drive.",
        ["rec_scan"] = "🔍  Scan deleted", ["rec_scanning"] = "Scanning deleted files…",
        ["rec_found"] = "Deleted files found: {0}", ["rec_empty"] = "No deleted files found",
        ["rec_all"] = "All",
        ["rec_recover"] = "♻  Recover selected", ["rec_recovering"] = "Recovering…",
        ["rec_done"] = "Recovered: {0}, failed: {1}", ["rec_nosel"] = "Nothing selected",
        ["rec_pickdest"] = "Where to recover (folder on ANOTHER drive)",
        ["rec_samedrive"] = "Can't recover to the same drive - choose another",
        ["rec_hint"] = "⚠ Recover to ANOTHER drive - otherwise data may be overwritten.",
        ["rec_high"] = "high", ["rec_mid"] = "medium", ["rec_low"] = "low", ["rec_wiped"] = "wiped",
        ["rcat_img"] = "🖼 Photos & images", ["rcat_video"] = "🎬 Video", ["rcat_audio"] = "🎵 Music",
        ["rcat_doc"] = "📄 Documents", ["rcat_archive"] = "🗜 Archives", ["rcat_prog"] = "⚙ Programs & libraries",
        ["rcat_other"] = "📦 Other",
        ["header_subtitle"] = "cleanup & optimization",
        // diagnostics — battery
        ["hdr_diag"] = "Diagnostics",
        ["report_btn"] = "📄 PC report",
        ["rep_title"] = "PC report",
        ["rep_generated"] = "Generated",
        ["rep_os"] = "System",
        ["rep_saved"] = "Saved: {0}",
        ["bat_title"] = "Battery health",
        ["bat_reading"] = "Reading battery report…",
        ["bat_none"] = "No battery detected (desktop PC).",
        ["bat_summary"] = "Wear {0}% of design capacity.",
        ["bat_wear"] = "Wear",
        ["bat_cycles"] = "Charge cycles",
        ["bat_cyc_na"] = "no data",
        ["bat_design"] = "Design capacity",
        ["bat_full"] = "Current max capacity",
        ["bat_charge"] = "Charge", ["bat_serial"] = "S/N {0}",
        ["bat_st_charging"] = "charging", ["bat_st_ac"] = "on AC", ["bat_st_batt"] = "on battery",
        ["bat_health_great"] = "Excellent condition", ["bat_health_ok"] = "Good, still healthy",
        ["bat_health_bad"] = "Heavily worn - consider replacing",
        ["u_wh"] = "Wh",
        // diagnostics — boot time
        ["boot_title"] = "Boot time",
        ["boot_reading"] = "Reading boot log…",
        ["boot_none"] = "No boot data (log empty or unavailable).",
        ["boot_time"] = "Last boot took {0} s.",
        ["boot_slow_head"] = "What slowed boot:",
        ["boot_slow_hint"] = "Each item's contribution to startup (includes background settling) - can exceed the total time.",
        ["boot_noslow"] = "No slowdowns detected.",
        ["u_sec"] = "s",
        ["boot_kind_app"] = "app",
        ["boot_kind_driver"] = "driver",
        ["boot_kind_service"] = "service",
        // maintenance
        ["hdr_maint"] = "System Maintenance",
        ["mnt_note"] = "Built-in Windows tools. Some take several minutes - the window stays responsive.",
        ["mnt_run"] = "Run",
        ["mnt_running"] = "Running…",
        ["mnt_done"] = "Done.",
        ["mnt_done_freed"] = "Done - component store cleaned.",
        ["mnt_fail"] = "Failed (administrator rights?).",
        ["mnt_ram_launched"] = "Memory Diagnostic opened - follow the prompt (a restart is needed).",
        ["mnt_sfc"] = "System File Check (SFC)",
        ["mnt_sfc_d"] = "Full system-file check (several minutes), repairs corrupted files",
        ["mnt_dism"] = "Image repair (DISM)",
        ["mnt_dism_d"] = "Check is instant; repair fixes the Windows component store",
        ["mnt_winsxs"] = "Component store cleanup (WinSxS)",
        ["mnt_winsxs_d"] = "Removes old update versions from WinSxS (often gigabytes). Safe - programs and Windows are untouched",
        ["mnt_defrag"] = "Optimize drives",
        ["mnt_defrag_d"] = "Defrag HDD & TRIM SSD (like Windows \"Optimize Drives\")",
        ["mnt_ram"] = "Memory test",
        ["mnt_ram_d"] = "Windows Memory Diagnostic (requires a restart)",
        ["mnt_check"] = "Check",
        ["mnt_cancel"] = "Cancel",
        ["mnt_analyzed"] = "Check complete. Run or cancel?",
        ["mnt_cancelled"] = "Cancelled.",
        ["mnt_r_sfc_clean"] = "No system file corruption found.",
        ["mnt_r_sfc_found"] = "Corrupted system files found - repair recommended.",
        ["mnt_r_sfc_unfixable"] = "Corruption found but SFC couldn't fix it - run DISM, then SFC again.",
        ["mnt_r_dism_clean"] = "No component store corruption found.",
        ["mnt_r_dism_repairable"] = "Component store corruption found - repair recommended.",
        ["mnt_r_winsxs_yes"] = "Superseded components present - cleanup will free space. Safe: only old update versions are removed, programs and Windows are untouched.",
        ["mnt_r_winsxs_yes_sz"] = "Can free ≈{0}. Safe: only old update versions are removed, programs and Windows are untouched.",
        ["mnt_r_winsxs_no"] = "No cleanup needed - the store is fine.",
        ["mnt_st_sfc_check"] = "Checking system files…",
        ["mnt_st_sfc_run"] = "Checking and repairing system files…",
        ["mnt_st_dism_check"] = "Scanning the component store…",
        ["mnt_st_dism_run"] = "Repairing the component store…",
        ["mnt_st_winsxs_check"] = "Analyzing the component store…",
        ["mnt_st_winsxs_run"] = "Removing superseded components…",
        ["mnt_st_defrag_check"] = "Analyzing disk fragmentation…",
        ["mnt_st_defrag_run"] = "Optimizing drives…",
        ["mnt_defrag_head"] = "Drive analysis:",
        ["mnt_op_ssd"] = "SSD, optimization (TRIM)",
        ["mnt_op_hdd"] = "HDD, defragmentation",
        ["mnt_op_line"] = "{0}: {1} - {2}, {3}",
        ["mnt_op_lastdays"] = "last run {0} d ago",
        ["mnt_op_lasttoday"] = "optimized today",
        ["mnt_op_lastunknown"] = "last run unknown",
        ["mnt_op_need"] = "recommended",
        ["mnt_op_ok"] = "not needed",
        ["mnt_defrag_noinfo"] = "Couldn't read drive info.",
        ["about_tagline"] = "Honest Windows cleanup & optimization",
        ["about_author"] = "Made by nak",
        ["about_version"] = "Version",
        ["upd_check"] = "Check for updates", ["upd_checking"] = "Checking for updates…",
        ["upd_latest"] = "You have the latest version", ["upd_available"] = "New version available: {0}",
        ["upd_fail"] = "Could not check for updates", ["upd_download"] = "Download update",
        ["theme_tip"] = "Theme: dark / light",
        ["lang_tip"] = "Switch language",
        ["glass"] = "Glass mode (Acrylic, Windows 11)",
        ["glass_hint"] = "Frosted glass blurring the desktop behind the window.",
        ["hdr_overview"] = "System Overview",
        ["hdr_clean"] = "System Cleanup",
        ["hdr_optimize"] = "Optimization",
        ["hdr_registry"] = "Registry Cleanup",
        ["hdr_startup"] = "Startup",
        ["hdr_apps"] = "Uninstall Programs",
        ["hdr_files"] = "File Search",
        ["hdr_health"] = "Disk Health (S.M.A.R.T.)",
        ["tile_cpu"] = "Processor",
        ["tile_ram"] = "Memory",
        ["tile_gpu"] = "Graphics",
        ["tile_disk"] = "Disk",
        ["tile_battery"] = "Battery",
        ["ov_os"] = "{0} · build {1}", ["ov_uptime"] = "up {0}",
        ["cap_load"] = "load",
        ["cap_used"] = "used",
        ["w_cores"] = "core|cores|cores",
        ["w_threads"] = "thread|threads|threads",
        ["w_modules"] = "module|modules|modules",
        ["u_gb"] = "GB",
        ["u_ghz"] = "GHz",
        ["u_mhz"] = "MHz",
        ["dh_temp"] = "TEMPERATURE",
        ["dh_hours"] = "POWER-ON HOURS",
        ["dh_wear"] = "WEAR (SSD)",
        ["dh_errors"] = "ERRORS",
        ["dh_admin"] = "⚠ Detailed metrics require running as administrator",
        ["dh_note"] = "Disks found: {0}. Data is current.",
        ["dh_note_empty"] = "No disks found (administrator rights required).",
        ["dh_na"] = "not reported",
        ["dh_read"] = "read",
        ["dh_write"] = "write",
        ["st_healthy"] = "Healthy",
        ["st_warning"] = "Warning",
        ["st_unhealthy"] = "Issues",
        ["st_unknown"] = "Unknown",
        ["u_h"] = "h",
        ["u_years"] = "y",
        ["u_days"] = "d",
        ["fs_tree"] = "Tree",
        ["fs_files"] = "Files",
        ["fs_browse"] = "📁 Browse…",
        ["fs_analyze"] = "🔎 Analyze",
        ["fs_up"] = "↑ Up",
        ["fs_c_folder"] = "FOLDER",
        ["fs_c_percent"] = "PERCENT",
        ["fs_c_size"] = "SIZE",
        ["fs_c_disk"] = "ON DISK",
        ["fs_c_files"] = "FILES",
        ["fs_c_types"] = "FILE TYPES",
        ["fs_c_name"] = "NAME",
        ["fs_c_folder2"] = "FOLDER   (double-click - open, right-click - menu)",
        ["opt_apply"] = "⚡ Apply selected",
        ["opt_revert"] = "↩ Revert",
        ["opt_restore"] = "Create a restore point before applying",
        ["opt_note"] = "Pick tweaks and click \"Apply\". A restore point is created before applying.",
        ["opt_applied"] = "Applied",
        ["opt_profiles"] = "Profiles:",
        ["prof_balanced"] = "Balanced",
        ["prof_gaming"] = "Gaming",
        ["prof_quiet"] = "Quiet",
        ["prof_clear"] = "Clear",
        ["opt_profile_set"] = "Profile selected: {0} tweaks. Review and click \"Apply\".",
        ["opt_profile_cleared"] = "Selection cleared.",
        ["chg_count"] = "Change log: tweaks applied — {0}",
        ["chg_revert_all"] = "↩ Revert all",
        ["chg_confirm"] = "Revert all logged changes ({0})? The system will return to its pre-optimization state.",
        ["chg_reverted"] = "Reverted: {0}.",
        ["tier_safe"] = "Safe",
        ["tier_medium"] = "Medium",
        ["tier_max"] = "Maximum",
        ["tw_anim"] = "Disable window animations", ["tw_anim_d"] = "Speeds up UI response",
        ["tw_transp"] = "Disable transparency", ["tw_transp_d"] = "Less GPU load",
        ["tw_tips"] = "Disable Windows tips & suggestions", ["tw_tips_d"] = "Removes intrusive notifications",
        ["tw_startdelay"] = "Remove startup delay", ["tw_startdelay_d"] = "Startup apps launch immediately",
        ["tw_explorerads"] = "Remove Explorer ads", ["tw_explorerads_d"] = "Disables \"sync provider notifications\"",
        ["tw_gamedvr"] = "Disable Game DVR / game recording", ["tw_gamedvr_d"] = "Fewer background processes in games",
        ["tw_bgapps"] = "Disable background apps", ["tw_bgapps_d"] = "Apps don't run in background unnecessarily",
        ["tw_telemetry"] = "Reduce telemetry", ["tw_telemetry_d"] = "Minimal data collection (policy)",
        ["tw_activity"] = "Disable activity history", ["tw_activity_d"] = "OS won't collect the activity feed",
        ["tw_sysmain"] = "Disable SysMain (Superfetch)", ["tw_sysmain_d"] = "Can speed up SSD systems; sometimes useful on HDD",
        ["tw_wsearch"] = "Disable indexing (Windows Search)", ["tw_wsearch_d"] = "Less disk load; search becomes slower",
        ["tw_diagtrack"] = "Disable telemetry service (DiagTrack)", ["tw_diagtrack_d"] = "Fully stops diagnostics collection",
        ["tw_hibernate"] = "Disable hibernation", ["tw_hibernate_d"] = "Frees disk space (removes hiberfil.sys)",
        // new tweaks (from the pack - only the ones that actually work)
        ["tw_menudelay"] = "Instant menu open", ["tw_menudelay_d"] = "MenuShowDelay=0 - menus open with no delay",
        ["tw_recording"] = "Disable background game recording", ["tw_recording_d"] = "Game DVR stops recording in the background - less load",
        ["tw_widgets"] = "Disable widgets (Windows 11)", ["tw_widgets_d"] = "The widgets process won't run in the background - saves RAM/CPU",
        ["tw_startads"] = "Remove ads & suggestions in Start", ["tw_startads_d"] = "Advertising ID + ContentDeliveryManager suggestions",
        ["tw_bgsearch"] = "Fully stop background apps", ["tw_bgsearch_d"] = "Finishes off background UWP apps (search toggle)",
        ["tw_netthrottle"] = "Disable network throttling", ["tw_netthrottle_d"] = "Helps audio/video + network combo (streaming, online)",
        ["tw_vbs"] = "Disable VBS (Memory Integrity)", ["tw_vbs_d"] = "Real 5-15% gain, BUT reduces memory protection",
        // honest effect labels
        ["eff_notable"] = "notable", ["eff_small"] = "minor", ["eff_space"] = "+space",
        ["eff_security"] = "−security", ["eff_convenience"] = "convenience",
        ["eff_notable_tip"] = "Notable performance gain - you'll actually feel it.",
        ["eff_small_tip"] = "Small but real effect: slightly snappier response or less RAM/CPU. Don't expect an FPS jump.",
        ["eff_space_tip"] = "Frees up disk space (no effect on speed).",
        ["eff_security_tip"] = "Speeds things up BUT lowers system security. Enable knowingly, at your own risk.",
        ["eff_convenience_tip"] = "Affects convenience and privacy, not performance.",
        ["btn_enable"] = "Enable", ["btn_disable"] = "Disable", ["btn_delete"] = "Delete",
        ["btn_select_all"] = "Select all", ["btn_select_none"] = "Clear all", ["btn_refresh"] = "↻  Refresh",
        ["btn_scan"] = "🔍  Scan", ["btn_clean"] = "🧹  Clean",
        ["c_on"] = "ON", ["c_program"] = "PROGRAM", ["c_publisher"] = "PUBLISHER", ["c_location"] = "LOCATION",
        ["c_command"] = "COMMAND", ["c_name"] = "NAME", ["c_author"] = "AUTHOR", ["c_state"] = "STATE",
        ["c_service"] = "SERVICE", ["c_iname"] = "NAME", ["c_start"] = "STARTUP", ["c_menuitem"] = "MENU ITEM", ["c_where"] = "WHERE",
        ["tip_expand"] = "Expand/collapse",
        ["pc_state"] = "PC Health", ["pc_recheck"] = "🔄  Re-check",
        ["verdict_great"] = "Excellent", ["verdict_good"] = "Good, room to improve",
        ["verdict_attention"] = "Needs attention", ["verdict_bad"] = "Many problems",
        ["pc_problems"] = "Issues", ["pc_warnings"] = "Warnings", ["pc_ok"] = "Healthy",
        ["clean_admin"] = "admin rights needed", ["clean_selected"] = "Selected to clean",
        ["sess_freed"] = "✓ Freed this session: {0}",
        ["grp_system"] = "System", ["grp_browsers"] = "Browsers", ["grp_traces"] = "Traces", ["grp_apps"] = "Apps",
        ["det_scanning"] = "scanning…", ["det_unscanned"] = "not scanned",
        ["det_items"] = "items", ["det_files"] = "files",
        ["reg_scan"] = "🔍  Scan for issues", ["reg_fix"] = "🛠  Fix selected", ["reg_notfound"] = "Entry not found",
        ["st_apps"] = "Programs", ["st_tasks"] = "Tasks", ["st_svc"] = "Services", ["st_ctx"] = "Context menu",
        ["st_yes"] = "Yes", ["st_no"] = "No",
        ["un_uninstall"] = "Uninstall", ["un_repair"] = "Repair", ["un_rename"] = "Rename", ["un_remove"] = "Remove from list",
        ["uc_program"] = "PROGRAM ▾", ["uc_publisher"] = "PUBLISHER ▾", ["uc_installed"] = "INSTALLED ▾", ["uc_size"] = "SIZE ▾", ["uc_version"] = "VERSION ▾",
        ["rp_dll"] = "Library file not found", ["rp_prog"] = "Program not found",
        ["rp_handler"] = "No handler \"{0}\"", ["rp_uninst"] = "Uninstaller not found ({0})",
        ["rp_startup"] = "Startup file not found", ["rp_font"] = "Font file not found",
        ["rp_sound"] = "Sound file not found", ["rp_help"] = "Help file not found",
        ["hc_mem"] = "Memory", ["hc_disks"] = "Disks", ["hc_sec"] = "Security", ["hc_hw"] = "Hardware", ["hc_sys"] = "System",
        ["hm_t"] = "RAM usage", ["hm_v"] = "{0}%  ({1} of {2})", ["hm_h"] = "Close unused programs or add more RAM.",
        ["hm_installed"] = "· {0} installed",
        ["hd_t"] = "Free space - {0}", ["hd_v"] = "{0} free ({1}%)", ["hd_h"] = "Free up space - clean junk or move files.",
        ["hs_h"] = "The disk may fail soon - make a backup!",
        ["hf_t"] = "Windows Defender", ["hf_on"] = "On, real-time protection active (defs: {0} d)",
        ["hf_on_fresh"] = "On, real-time protection active (defs up to date)",
        ["hf_off"] = "Protection disabled", ["hf_err"] = "Could not check (may need admin rights, or a third-party antivirus is installed)",
        ["hf_h_bad"] = "Enable antivirus or install one.", ["hf_h_warn"] = "Update antivirus definitions.",
        ["hdr_t"] = "Device drivers", ["hdr_ok"] = "No problems found", ["hdr_bad"] = "Devices with errors: {0}",
        ["hdr_h"] = "Check Device Manager - some devices have problems.",
        ["hu_t"] = "Uptime since last reboot", ["hu_vd"] = "{0} d {1} h", ["hu_vh"] = "{0} h {1} min",
        ["hu_h"] = "Not rebooted in a while - a restart will refresh the system.",
        ["hb_t"] = "Battery", ["hb_v"] = "Charge: {0}%", ["hb_none"] = "Not detected (desktop PC)",
        ["hj_t"] = "Temporary files (%TEMP%)", ["hj_v"] = "{0} of junk", ["hj_h"] = "Open the Cleanup tab and remove junk.",
        ["ho_t"] = "Operating system", ["ho_v"] = "{0} (build {1})",
        ["note_status"] = "Ready. Click \"Scan\" to estimate junk.",
        ["note_reg"] = "Pick categories and click \"Scan for issues\". A backup is made before removal.",
        ["note_scan"] = "Pick a drive or folder and click \"Analyze\".",
        ["note_healthcheck"] = "Checking the system…",
        // cleanup categories (EN only - RU comes from CleanEngine literals)
        ["cat_temp_user"] = "Temporary files (user)", ["catd_temp_user"] = "The %TEMP% folder - the most common source of junk",
        ["cat_temp_win"] = "Windows temporary files", ["catd_temp_win"] = "Windows\\Temp - the system-wide temp folder",
        ["cat_recycle"] = "Recycle Bin", ["catd_recycle"] = "Deleted files still taking up space",
        ["cat_crashdumps"] = "Crash dumps & error reports", ["catd_crashdumps"] = "CrashDumps - snapshots of crashed programs",
        ["cat_thumbnails"] = "Thumbnail cache", ["catd_thumbnails"] = "thumbcache_*.db - Explorer thumbnails",
        ["cat_prefetch"] = "Prefetch", ["catd_prefetch"] = "App preload data (Windows will recreate it)",
        ["cat_winupdate"] = "Windows Update cache", ["catd_winupdate"] = "SoftwareDistribution\\Download - downloaded updates",
        ["cat_recent"] = "Recent documents", ["catd_recent"] = "Shortcuts in the \"recent\" list (history, not files)",
        ["cat_wer"] = "Windows Error Reports (WER)", ["catd_wer"] = "Application crash report archives",
        ["cat_shadercache"] = "GPU shader cache", ["catd_shadercache"] = "DirectX / NVIDIA / AMD - recreated automatically",
        ["cat_winlogs"] = "Windows system logs", ["catd_winlogs"] = "Windows\\Logs - setup & servicing logs",
        ["cat_winold"] = "Windows.old folder", ["catd_winold"] = "Old Windows copy after upgrade (can be tens of GB)",
        ["cat_chrome"] = "Google Chrome cache", ["catd_chrome"] = "Page & code cache (history & passwords untouched)",
        ["cat_edge"] = "Microsoft Edge cache", ["catd_edge"] = "Edge page cache",
        ["cat_firefox"] = "Mozilla Firefox cache", ["catd_firefox"] = "cache2 - Firefox page cache",
        ["cat_jumplists"] = "Jump lists", ["catd_jumplists"] = "Recent-files history in the taskbar & Start",
        ["cat_brave"] = "Brave cache", ["catd_brave"] = "Brave page & code cache",
        ["cat_opera"] = "Opera cache", ["catd_opera"] = "Opera page cache",
        ["cat_discord"] = "Discord cache", ["catd_discord"] = "Page, code & GPU cache (chat history untouched)",
        ["cat_spotify"] = "Spotify cache", ["catd_spotify"] = "Cached downloaded data (playlists stay)",
        ["cat_teams"] = "Microsoft Teams cache", ["catd_teams"] = "Page, code, GPU & attachment cache",
        ["cat_slack"] = "Slack cache", ["catd_slack"] = "Page & service-worker cache",
        ["cat_steam_shader"] = "Steam shader cache", ["catd_steam_shader"] = "shadercache - recreated when games launch",
        // registry categories (EN only)
        ["rcat_shareddll"] = "Missing shared DLLs", ["rcat_apppaths"] = "Application paths",
        ["rcat_fileext"] = "Unused file extensions", ["rcat_uninstall"] = "Obsolete applications",
        ["rcat_startup"] = "Startup", ["rcat_fonts"] = "Fonts", ["rcat_sound"] = "Sound events",
        ["rcat_mui"] = "MUI cache", ["rcat_help"] = "Help files",
        ["cap_of100"] = "of 100",
        // about
        ["about_version_fmt"] = "Version {0}",
        // runtime - common
        ["err"] = "Error: {0}",
        // PC health
        ["hc_ok"] = "No problems found.",
        ["hc_found"] = "Issues found: {0}. Details below.",
        ["hc_err"] = "Check failed: {0}",
        // startup
        ["su_default"] = "Programs that launch with Windows.",
        ["su_count"] = "Entries: {0} (enabled: {1}).",
        ["su_on"] = "\"{0}\" enabled at startup.",
        ["su_off"] = "\"{0}\" disabled.",
        ["su_fail_admin"] = "Couldn't change \"{0}\" - run NakClean as administrator.",
        ["su_fail"] = "Couldn't change \"{0}\".",
        ["su_del_q"] = "Remove \"{0}\" from startup?\nThis deletes the entry permanently (the program is not uninstalled).",
        ["su_deleted"] = "\"{0}\" removed from startup.",
        ["su_del_fail_admin"] = "Couldn't delete \"{0}\" - administrator rights required.",
        ["su_del_fail"] = "Couldn't delete \"{0}\".",
        // uninstall programs
        ["ap_default"] = "Installed programs.",
        ["ap_count"] = "Installed programs: {0}.",
        ["ap_repair_ok"] = "Repair started for \"{0}\".",
        ["ap_repair_no"] = "Repair is not available for \"{0}\".",
        ["ap_rename_prompt"] = "New entry name:",
        ["ap_renamed"] = "Entry renamed.",
        ["ap_rename_fail"] = "Couldn't rename - administrator rights may be required.",
        ["ap_remove_q"] = "Remove \"{0}\" from the list?\nThis only deletes the registry entry - the program itself is NOT uninstalled.",
        ["ap_removed"] = "Entry removed from the list.",
        ["ap_remove_fail"] = "Couldn't remove the entry - administrator rights may be required.",
        ["ap_uninst_q"] = "Launch the uninstaller for \"{0}\"?",
        ["ap_uninst_ok"] = "Uninstaller for \"{0}\" started. Follow its steps, then click \"Refresh\".",
        ["ap_uninst_fail"] = "Couldn't launch the uninstaller for \"{0}\".",
        // registry
        ["reg_nocat"] = "No category selected.",
        ["reg_scanning"] = "Scanning the registry for issues…",
        ["reg_clean"] = "No issues found - the registry is clean.",
        ["reg_found"] = "Issues found: {0}. Review the list and click \"Fix selected\".",
        ["reg_scan_err"] = "Scan error: {0}",
        ["reg_nofix"] = "Nothing selected to fix.",
        ["reg_fix_q"] = "A backup (.reg) will be created and {0} entries removed.\nYou can undo by double-clicking the backup file.\n\nContinue?",
        ["reg_fix_title"] = "NakClean - registry cleanup",
        ["reg_fixing"] = "Creating a backup and removing entries…",
        ["reg_removed"] = "Removed: {0}.",
        ["reg_failed"] = " Failed: {0} (administrator rights may be required).",
        ["reg_backup_saved"] = " Backup saved.",
        ["reg_done_box"] = "Done.\nEntries removed: {0}\nFailed: {1}\n\nBackup:\n{2}\n\nTo undo everything - close NakClean and double-click this .reg file.",
        ["reg_fix_err"] = "Fix error: {0}",
        // scheduled tasks
        ["tk_default"] = "Scheduled tasks (non-system).",
        ["tk_count"] = "Tasks: {0} (enabled: {1}).",
        ["tk_on"] = "Task \"{0}\" enabled.",
        ["tk_off"] = "Task \"{0}\" disabled.",
        ["tk_fail"] = "Couldn't change \"{0}\" - run as administrator.",
        ["tk_del_q"] = "Delete task \"{0}\"?",
        ["tk_deleted"] = "Task deleted.",
        ["tk_del_fail"] = "Couldn't delete - administrator rights required.",
        // services
        ["sv_default"] = "Windows services. Caution: disabling system services can cause harm.",
        ["sv_count"] = "Services: {0}. Be careful disabling system ones.",
        ["sv_enable_q"] = "Enable service \"{0}\" (automatic start + run)?",
        ["sv_disable_q"] = "Disable service \"{0}\"?\nDisabling a system service can break Windows.",
        ["sv_title"] = "NakClean - services",
        ["sv_applying"] = "Applying…",
        ["sv_fail"] = "Couldn't change \"{0}\" - administrator rights required.",
        ["sv_on_run"] = "\"{0}\" enabled and running.",
        ["sv_on_notrun"] = "\"{0}\": automatic start enabled (service hasn't started yet).",
        ["sv_off_run"] = "\"{0}\": start disabled, will stop after a reboot.",
        ["sv_off_stop"] = "\"{0}\" disabled and stopped.",
        // context menu
        ["cx_default"] = "Explorer context-menu items.",
        ["cx_count"] = "Items: {0} (enabled: {1}).",
        ["cx_on"] = "\"{0}\" enabled.",
        ["cx_off"] = "\"{0}\" disabled.",
        ["cx_fail"] = "Couldn't change \"{0}\" - administrator rights required.",
        ["cx_del_q"] = "Remove item \"{0}\" from the context menu?\nA .reg backup will be created.",
        ["cx_deleted"] = "Item removed (backup created).",
        ["cx_del_fail"] = "Couldn't delete - administrator rights required.",
        // optimization
        ["opt_none"] = "Nothing selected.",
        ["opt_max_q"] = "Your selection includes \"Maximum\" tweaks - they change the behavior of system services.\nEverything is reversible. Continue?",
        ["opt_title"] = "NakClean - optimization",
        ["opt_rp_creating"] = "Creating a restore point…",
        ["opt_rp_name"] = "NakClean - before optimization",
        ["opt_rp_ok"] = " Restore point created.",
        ["opt_rp_fail"] = " Couldn't create a restore point (enable System Protection in PC properties).",
        ["opt_applying"] = "Applying…",
        ["opt_reverting"] = "Reverting…",
        ["opt_applied_n"] = "Applied: {0}/{1}.",
        ["opt_reverted_n"] = "Reverted: {0}/{1}.",
        ["opt_after"] = " Some changes take effect after sign-out/restart.",
        // file search
        ["fs_notarget"] = "- none -",
        ["fs_localdisk"] = "Local Disk",
        ["fs_pickfolder"] = "Pick a folder to analyze",
        ["fs_badpath"] = "Folder or drive not found - check the path.",
        ["fs_analyzing"] = "Analyzing…",
        ["fs_stats"] = "Files: {0}   ·   Size: {1}   ·   On disk: {2}",
        ["fs_drive"] = "Volume: {0} of {1} used ({2}%), {3} free",
        ["fs_done"] = "Done in {0} s.",
        ["map_title"] = "Disk map will appear after analysis",
        // cleanup
        ["cl_scanning"] = "Scanning…",
        ["cl_found"] = "Junk found: {0}. Review the selection and click \"Clean\".",
        ["cl_cancelled"] = "Scan cancelled.",
        ["cl_scan_err"] = "Scan error: {0}",
        ["cl_cleaning"] = "Cleaning…",
        ["cl_done"] = "Done. Freed: {0}.",
        ["cl_interrupted"] = "Cleanup interrupted. Freed: {0}.",
        ["cl_clean_err"] = "Cleanup error: {0}",
        // file context menu (right-click in File Search)
        ["ctx_open"] = "Open",
        ["ctx_open_folder"] = "Open folder",
        ["ctx_reveal"] = "Show in Explorer",
        ["ctx_openwith"] = "Open with…",
        ["ctx_copypath"] = "Copy path",
        ["ctx_props"] = "Properties",
        // services - start mode
        ["sm_auto"] = "Auto",
        ["sm_manual"] = "Manual",
        ["sm_disabled"] = "Disabled",
        // startup - source
        ["su_folder_user"] = "Folder (user)",
        ["su_folder_common"] = "Folder (common)",
        // context menu - where
        ["cmw_files"] = "Files",
        ["cmw_folders"] = "Folders",
        ["cmw_folderbg"] = "Folder background",
        ["cmw_drives"] = "Drives",
        ["cmw_allobjects"] = "All objects",
        // file search - types
        ["fs_noext"] = "(no extension)",
        ["fs_typefile"] = "File",
        ["fs_typesuffix"] = " file",
        // misc
        ["na"] = "n/a",
        ["u_mb"] = "MB",
        ["app_error"] = "An error occurred, but the app will keep running:\n\n{0}",
    };
}
