namespace NakClean.Services;

/// <summary>Понятные названия атрибутов SMART (ATA) и полей журнала NVMe - RU/EN.</summary>
public static class SmartNames
{
    private static readonly Dictionary<int, (string ru, string en)> Ata = new()
    {
        [1] = ("Частота ошибок чтения", "Raw Read Error Rate"),
        [2] = ("Производительность", "Throughput Performance"),
        [3] = ("Время раскрутки", "Spin-Up Time"),
        [4] = ("Число запусков/остановок", "Start/Stop Count"),
        [5] = ("Переназначенные секторы", "Reallocated Sectors Count"),
        [7] = ("Ошибки позиционирования", "Seek Error Rate"),
        [8] = ("Скорость позиционирования", "Seek Time Performance"),
        [9] = ("Часы работы", "Power-On Hours"),
        [10] = ("Повторы раскрутки", "Spin Retry Count"),
        [11] = ("Повторы калибровки", "Calibration Retry Count"),
        [12] = ("Число включений", "Power Cycle Count"),
        [13] = ("Программные ошибки чтения", "Soft Read Error Rate"),
        [160] = ("Неисправимые секторы", "Uncorrectable Sector Count"),
        [161] = ("Доступный резерв", "Valid Spare Blocks"),
        [163] = ("Начальные плохие блоки", "Initial Bad Blocks"),
        [164] = ("Всего циклов стирания", "Total Erase Count"),
        [165] = ("Макс. циклов стирания", "Max Erase Count"),
        [166] = ("Мин. циклов стирания", "Min Erase Count"),
        [167] = ("Среднее циклов стирания", "Average Erase Count"),
        [168] = ("Предел циклов стирания", "Max Erase Count of Spec"),
        [169] = ("Остаток ресурса", "Remaining Life"),
        [170] = ("Доступный резерв", "Available Reserved Space"),
        [171] = ("Ошибки программирования", "Program Fail Count"),
        [172] = ("Ошибки стирания", "Erase Fail Count"),
        [173] = ("Выравнивание износа", "Wear Leveling Count"),
        [174] = ("Внезапные отключения питания", "Unexpected Power Loss Count"),
        [175] = ("Сбои защиты от потери питания", "Power Loss Protection Failure"),
        [176] = ("Ошибки стирания", "Erase Fail Count"),
        [177] = ("Выравнивание износа", "Wear Leveling Count"),
        [178] = ("Использовано резервных блоков (чип)", "Used Reserved Block Count (Chip)"),
        [179] = ("Использовано резервных блоков", "Used Reserved Block Count"),
        [180] = ("Свободно резервных блоков", "Unused Reserved Block Count"),
        [181] = ("Ошибки программирования", "Program Fail Count Total"),
        [182] = ("Ошибки стирания", "Erase Fail Count Total"),
        [183] = ("Сбойные блоки / снижение скорости SATA", "Runtime Bad Block / SATA Downshift"),
        [184] = ("Сквозные ошибки", "End-to-End Error"),
        [187] = ("Неисправимые ошибки", "Reported Uncorrectable Errors"),
        [188] = ("Тайм-ауты команд", "Command Timeout"),
        [189] = ("Запись при высоком полёте головки", "High Fly Writes"),
        [190] = ("Температура воздуха", "Airflow Temperature"),
        [191] = ("Ударные нагрузки", "G-Sense Error Rate"),
        [192] = ("Аварийные выключения", "Power-off Retract Count"),
        [193] = ("Циклы парковки головок", "Load/Unload Cycle Count"),
        [194] = ("Температура", "Temperature"),
        [195] = ("Исправлено ECC", "Hardware ECC Recovered"),
        [196] = ("События переназначения", "Reallocation Event Count"),
        [197] = ("Нестабильные секторы", "Current Pending Sector Count"),
        [198] = ("Неисправимые секторы", "Uncorrectable Sector Count"),
        [199] = ("Ошибки CRC интерфейса (кабель)", "UltraDMA CRC Error Count"),
        [200] = ("Ошибки записи", "Write Error Rate"),
        [202] = ("Остаток ресурса", "Percent Lifetime Remaining"),
        [206] = ("Высота полёта головки", "Flying Height"),
        [210] = ("Ошибки RAID-восстановления", "RAID Recovery Count"),
        [220] = ("Смещение диска", "Disk Shift"),
        [222] = ("Часы под нагрузкой", "Loaded Hours"),
        [223] = ("Повторы загрузки/выгрузки", "Load/Unload Retry Count"),
        [225] = ("Циклы загрузки/выгрузки", "Load/Unload Cycle Count"),
        [226] = ("Время под нагрузкой", "Load-in Time"),
        [230] = ("Амплитуда головки / ресурс", "GMR Head Amplitude / Life Curve"),
        [231] = ("Остаток ресурса SSD", "SSD Life Left"),
        [232] = ("Доступный резерв", "Available Reserved Space"),
        [233] = ("Индикатор износа носителя", "Media Wearout Indicator"),
        [234] = ("Среднее/макс. стираний", "Average/Max Erase Count"),
        [235] = ("Восстановления после сбоя питания", "POR Recovery Count"),
        [240] = ("Время полёта головки", "Head Flying Hours"),
        [241] = ("Всего записано", "Total Host Writes"),
        [242] = ("Всего прочитано", "Total Host Reads"),
        [243] = ("Всего записано (расш.)", "Total Host Writes Expanded"),
        [244] = ("Всего прочитано (расш.)", "Total Host Reads Expanded"),
        [245] = ("Остаток ресурса", "Remaining Rated Write Endurance"),
        [246] = ("Всего записано секторов", "Total Host Sector Writes"),
        [247] = ("Страниц записано хостом", "Host Program Page Count"),
        [248] = ("Страниц записано контроллером", "FTL Program Page Count"),
        [249] = ("Записано в NAND", "NAND Writes"),
        [250] = ("Повторы чтения", "Read Error Retry Rate"),
        [251] = ("Мин. остаток резерва", "Minimum Spares Remaining"),
        [252] = ("Новые плохие блоки", "Newly Added Bad Flash Block"),
        [254] = ("Защита от падения", "Free Fall Protection"),
    };

    private static readonly Dictionary<int, (string ru, string en)> Nvme = new()
    {
        [0x01] = ("Критическое предупреждение", "Critical Warning"),
        [0x02] = ("Температура", "Composite Temperature"),
        [0x03] = ("Доступный резерв", "Available Spare"),
        [0x04] = ("Порог резерва", "Available Spare Threshold"),
        [0x05] = ("Израсходовано ресурса", "Percentage Used"),
        [0x06] = ("Прочитано данных", "Data Units Read"),
        [0x07] = ("Записано данных", "Data Units Written"),
        [0x08] = ("Команд чтения", "Host Read Commands"),
        [0x09] = ("Команд записи", "Host Write Commands"),
        [0x0A] = ("Время занятости контроллера", "Controller Busy Time"),
        [0x0B] = ("Число включений", "Power Cycles"),
        [0x0C] = ("Часы работы", "Power On Hours"),
        [0x0D] = ("Небезопасные выключения", "Unsafe Shutdowns"),
        [0x0E] = ("Ошибки целостности данных", "Media and Data Integrity Errors"),
        [0x0F] = ("Записей в журнале ошибок", "Error Information Log Entries"),
    };

    public static string Name(int id, bool nvme)
    {
        var table = nvme ? Nvme : Ata;
        if (table.TryGetValue(id, out var n)) return Loc.I.IsEn ? n.en : n.ru;
        return Loc.I.IsEn ? "Vendor specific" : "Атрибут производителя";
    }
}
